from kivy.uix.widget import Widget
from kivy.uix.label import Label
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.textinput import TextInput
from kivy.uix.scrollview import ScrollView
from kivy.uix.gridlayout import GridLayout
from kivy.uix.popup import Popup

from kivy.app import App
class CalorieCount(App):

#okay so this is going to be a GUI with only ONE GUI to make it less complicated, it is going to ask and answer all the questions on the first box

